# Generated by Django 2.2.4 on 2019-10-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
