# Generated by Django 2.2.4 on 2019-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='courses')),
                ('lessons', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('offer', models.BooleanField(default=False)),
                ('offerAmount', models.IntegerField()),
            ],
        ),
    ]
